# Manipulação de Array

### Array

In [1]:
import numpy as np

In [47]:
lista = [1,2,3,4,5,6]
array = np.array(lista)

In [48]:
#Diferença entre lista e array
print (lista)
print(array)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [4]:
#Preenchendo uma array de zeros
arr_zeros = np.zeros(15)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [49]:
print(array[0])

1


In [50]:
#editar o texto
array [0] = 20

In [51]:
array

array([20,  2,  3,  4,  5,  6])

### Matriz

In [8]:
#Matriz de zeros
matriz_zeros = np.zeros((5,3))

In [9]:
matriz_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Tendo em vista um array com notas é possível fazer as seguintes operações com funções NumPy

In [52]:

notas = [30,33,55,22,31,55]
notas = np.array(notas)
print(type(notas))
print('Maxímo', notas.max())
print('Mínimo', notas.min())
print('Desvio Padrão', notas.std())
print('Media', notas.mean())
print('Posicao menor', notas.argmin())

<class 'numpy.ndarray'>
Maxímo 55
Mínimo 22
Desvio Padrão 12.723556455994876
Media 37.666666666666664
Posicao menor 3


## Exercício

### 1º Peça ao usuário para digitar alguns números, transforme em array e utilize funções do Numpy

In [11]:
print ('Digite 10 números')
lista = []
for i in range(10):
    i = input(f'{i+1}º número ')
    lista.append(int(i))

Digite 10 números
1º número 2
2º número 4
3º número 44
4º número 5
5º número 33
6º número 22
7º número 33
8º número 11
9º número 0
10º número -8


In [23]:
lista

array([ 2,  4, 44,  5, 33, 22, 33, 11,  0, -8])

In [24]:
lista = np.array(lista)

In [25]:
lista

array([ 2,  4, 44,  5, 33, 22, 33, 11,  0, -8])

In [26]:
print('Maxímo',lista.max())
print('Mínimo',lista.min())
print('Desvio padrão', lista.std())
print('Média', lista.mean())
print('Onde está o número de menor posição? Está na', lista.argmax(), 'º posição')

Maxímo 44
Mínimo -8
Desvio padrão 16.42071862008481
Média 14.6
Onde está o número de menor posição? Está na 2 º posição


# Máscaras Booleana

A máscara Booleana funciona como um filtro

In [34]:
is_covid_positive = np.array(['yyy','n','yyy','yyy','n', 'n','n'])

In [35]:
#Seleciona apenas os indices com esse valor:
mask = (is_covid_positive == 'yyy')

In [36]:
#Editando todos os valores com valor "yyy" para "C19". OBS: Só da para substituir por um string com o mesmo número de digitos
is_covid_positive[mask] = 'C19'

In [37]:
print(is_covid_positive[mask])

['C19' 'C19' 'C19']


In [38]:
#Imprimindo a nova lista
print(is_covid_positive)

['C19' 'n' 'C19' 'C19' 'n' 'n' 'n']


In [39]:
#Criando uma váriavel para receber os valores da máscara
positivo = is_covid_positive[is_covid_positive == 'C19']

In [40]:
positivo

array(['C19', 'C19', 'C19'], dtype='<U3')